### ISSUE TITLE
16.patch uri is dead

### ISSUE THREAD

**Issue by Abbotta4** [sigmaboy/nopaystation_scripts#1]
The README.md lists [this patch](https://github.com/mmozeiko/pkg2zip/pull/16.patch) for pkg2zip as a requirement for using these scripts, but the patch no longer exists. Was the patch merged in the current release, or is the patch still necessary?

**Comment by sigmaboy** [comment]
The patch was merged into master.
Thank you for opening the issue.
Next update will follow
