### ISSUE TITLE
[Feature Request] Docs on how to make pkg2zip for linux debian

### ISSUE THREAD

**Issue by robzombie91** [sigmaboy/nopaystation_scripts#3]
Took me a bit to figure out but i ended up making it in the end

git clone https://github.com/mmozeiko/pkg2zip
cd pkg2zip
make
sudo cp pkg2zip /usr/bin

**Comment by sigmaboy** [comment]
you should add a submit request to pkg2zip to create a #build section in the README:md which explains the build process more detailed.

Btw: You also should install of the binary correctly:
sudo install -o root -g root -m 0755 pkg2zip /usr/local/bin/

(Self-compiled programs should be installed to /usr/local/)

Thank you for your help
